"""add user profile and signature fields

Revision ID: 7dba13c5edeb
Revises: 002_timezone_support
Create Date: 2026-02-02 01:49:53.332339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dba13c5edeb'
down_revision: Union[str, None] = '002_timezone_support'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_tags_campaign_id'), table_name='campaign_tags')
    op.drop_index(op.f('ix_campaign_tags_tag'), table_name='campaign_tags')
    op.drop_table('campaign_tags')
    op.drop_index(op.f('ix_email_jobs_status_scheduled_at'), table_name='email_jobs')
    op.add_column('users', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('users', sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('users', sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('users', sa.Column('email_signature', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'email_signature')
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.create_index(op.f('ix_email_jobs_status_scheduled_at'), 'email_jobs', ['status', 'scheduled_at'], unique=False)
    op.create_table('campaign_tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('campaign_tags_campaign_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('campaign_tags_pkey'))
    )
    op.create_index(op.f('ix_campaign_tags_tag'), 'campaign_tags', ['tag'], unique=False)
    op.create_index(op.f('ix_campaign_tags_campaign_id'), 'campaign_tags', ['campaign_id'], unique=False)
    # ### end Alembic commands ###
